const EMAIL_MAX_LENGTH = 50
const PASSWORD_MIN_LENGTH = 5
const PASSWORD_MAX_LENGTH = 50
const PASSWORD_LOWERCASE = /^(?=.*[a-z])/
const PASSWORD_UPPERCASE = /^(?=.*[A-Z])/
const PASSWORD_NUMBER = /^(?=.*[0-9])/
const PASSWORD_SPECIAL_CASE = /^(?=.*[!@#$%^&*])/

export const REGEX = {
    EMAIL_MAX_LENGTH,
    PASSWORD_MIN_LENGTH,
    PASSWORD_MAX_LENGTH,
    PASSWORD_LOWERCASE,
    PASSWORD_UPPERCASE,
    PASSWORD_NUMBER,
    PASSWORD_SPECIAL_CASE,
}

const EMAIL_RULE_MESSAGE_TO_LONG= 'Too Short. Min length 5 symbol'
const EMAIL_RULE_MESSAGE_NOT_VALID = 'Too Long. Max length 50 symbol'
const EMAIL_RULE_MESSAGE_REQUIRED = 'Required'

const PASSWORD_RULE_MESSAGE_MIN_LENGTH = 'Too Short. Min length 5 symbol'
const PASSWORD_RULE_MESSAGE_MAX_LENGTH = 'Too Long. Max length 50 symbol'
const PASSWORD_RULE_MESSAGE_LOWERCASE = 'Must one Lowercase'
const PASSWORD_RULE_MESSAGE_UPPERCASE = 'Must one Uppercase'
const PASSWORD_RULE_MESSAGE_NUMBER = 'Must One Number'
const PASSWORD_RULE_MESSAGE_SPECIAL_CASE = 'Must One Special Case Character(@, #, $, %, ^ ,&, *)'
const PASSWORD_RULE_MESSAGE_MISMATCH = 'Password mismatch'
const PASSWORD_RULE_MESSAGE_REQUIRED = 'Required'

export const MESSAGE = {
    EMAIL_RULE_MESSAGE_TO_LONG,
    EMAIL_RULE_MESSAGE_NOT_VALID,
    EMAIL_RULE_MESSAGE_REQUIRED,
    PASSWORD_RULE_MESSAGE_MIN_LENGTH,
    PASSWORD_RULE_MESSAGE_MAX_LENGTH,
    PASSWORD_RULE_MESSAGE_LOWERCASE,
    PASSWORD_RULE_MESSAGE_UPPERCASE,
    PASSWORD_RULE_MESSAGE_NUMBER,
    PASSWORD_RULE_MESSAGE_SPECIAL_CASE,
    PASSWORD_RULE_MESSAGE_MISMATCH,
    PASSWORD_RULE_MESSAGE_REQUIRED,
}